### ISSUE TITLE
Cannot use images with dot:  Service Unavailable

### ISSUE THREAD

**Issue by rgruyters** [ivanilves/lstags#199]
I have an issue when I want to pull rocket.chat images from the Docker hub.

```
time="2019-09-17T10:02:13Z" level=info msg="ANALYZE rocket.chat~/^1\\.\\d+\\.(\\d+)?/"
Get https://rocket.chat~/v2/: Service Unavailable
```

lstags want to use the image name as a remote repository. Tried to add `docker.io/rocket.chat` as image name but then I get an index out of range message.

```
INFO[0000] BATCH 1 of 1                                 
INFO[0000] ANALYZE docker.io/rocket.chat~/^1\.\d+\.(\d+)?/ 
panic: runtime error: index out of range

goroutine 18 [running]:
github.com/ivanilves/lstags/api/v1/registry/client/request.getNextLink(0xc000054580, 0x4, 0x4, 0x4, 0xc000296df0)
        /go/src/github.com/ivanilves/lstags/api/v1/registry/client/request/request.go:122 +0x102
github.com/ivanilves/lstags/api/v1/registry/client/request.Perform(0xc0000adc20, 0x2a, 0xc000230320, 0x5, 0x868d9c, 0x2, 0x0, 0x2, 0x6fc23ac00, 0x811260, ...)
        /go/src/github.com/ivanilves/lstags/api/v1/registry/client/request/request.go:88 +0x397
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).TagData(0xc0002d7960, 0xc0000adbca, 0xb, 0x0, 0x0, 0x0, 0x0, 0xc0002d7960, 0x0)
        /go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:199 +0x37b
github.com/ivanilves/lstags/tag/remote.FetchTags(0xc000208c00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/ivanilves/lstags/tag/remote/remote.go:69 +0x191
github.com/ivanilves/lstags/api/v1.(*API).CollectTags.func1(0xc000208840, 0xc000208ae0, 0xc000208c00, 0xc000208c60)
        /go/src/github.com/ivanilves/lstags/api/v1/v1.go:169 +0x13e
created by github.com/ivanilves/lstags/api/v1.(*API).CollectTags
        /go/src/github.com/ivanilves/lstags/api/v1/v1.go:164 +0x318

```

I'm using lstags version 1.2.7.

**Comment by ivanilves** [comment]
Thanks for sharing this! - Will try to review and fix ASAP.
