### ISSUE TITLE
Crash when pushing

### ISSUE THREAD

**Issue by davidcorbin** [ivanilves/lstags#213]
Have been struggling to get this tool working to pull from a public repo and push to a private repo. Also came across this issue.

```bash
➜  Downloads ./lstags -k -P quay.io/coreos/flannel:v0.11.0-amd64 -R https://example.com/v2/demo/asdf
INFO[0000] BATCH 1 of 1
INFO[0000] ANALYZE quay.io/coreos/flannel:v0.11.0-amd64
[credhelper][credsStore] Error: exit status 1
INFO[0005] FETCHED quay.io/coreos/flannel:v0.11.0-amd64
-
<STATE>      <DIGEST>                                      <(local) ID>    <Created At>              <IMAGE>:<TAG>
PRESENT      sha256:7806805c93b20a168d0bbbd25c6a213f0      ff281650a721    2019-01-28T14:48:19-05:00 quay.io/coreos/flannel:v0.11.0-amd64
-
INFO[0005] [PULL/PUSH] ANALYZE quay.io/coreos/flannel:v0.11.0-amd64 => /https://example.com/v2/demo/asdf/coreos/flannel~/.*/
[credhelper][credsStore] Error: exit status 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13f904a]

goroutine 97 [running]:
github.com/ivanilves/lstags/repository.(*Repository).Registry(...)
	/go/src/github.com/ivanilves/lstags/repository/repository.go:59
github.com/ivanilves/lstags/tag/remote.FetchTags(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/ivanilves/lstags/tag/remote/remote.go:51 +0x3a
github.com/ivanilves/lstags/api/v1.(*API).CollectPushTags.func1(0xc000070fd0, 0x1, 0x1, 0xc0000883c0, 0x7ffeefbffacf, 0x2f, 0x0, 0x0, 0x0, 0x14d8c4e, ...)
	/go/src/github.com/ivanilves/lstags/api/v1/v1.go:279 +0x518
created by github.com/ivanilves/lstags/api/v1.(*API).CollectPushTags
	/go/src/github.com/ivanilves/lstags/api/v1/v1.go:257 +0x4cb
➜  Downloads ./lstags --version
VERSION: v1.2.11
```

**Comment by ivanilves** [comment]
Thanks for reporting! Probably related to https://github.com/ivanilves/lstags/issues/214 

Could you please try to use older version `1.2.10` and report if any changes in behavior? :pray:

**Comment by ivanilves** [comment]
This issue fixed: https://github.com/ivanilves/lstags/releases/tag/v1.2.12

This was not a bug rather a gap in validation / error handling.
