### ISSUE TITLE
Error when specifying docker.io as registry

### ISSUE THREAD

**Issue by cablespaghetti** [ivanilves/lstags#224]
Where I have generated my config.yaml from what is running in my Kubernetes cluster through the magic of Bash, some of the images from Docker Hub are specified in this format: `docker.io/bitnami/zookeeper:3.6.1-debian-10-r37`

This does not please the Go gods :(
```
INFO[0000] BATCH 1 of 1                                 
INFO[0000] ANALYZE docker.io/bitnami/zookeeper:3.6.1-debian-10-r37 
INFO[0000] ANALYZE busybox=1.29.3,latest                
INFO[0000] ANALYZE cassandra:3.11.6                     
INFO[0000] ANALYZE banzaicloud/bank-vaults:1.4.0        
INFO[0000] ANALYZE alpine:latest                        
INFO[0000] ANALYZE confluentinc/cp-kafka:5.5.0          
INFO[0000] ANALYZE danielqsj/kafka-exporter:v1.2.0      
INFO[0000] ANALYZE docker.elastic.co/elasticsearch/elasticsearch:7.7.1 
INFO[0000] ANALYZE docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4 
INFO[0000] ANALYZE banzaicloud/vault-env:1.3.0          
INFO[0000] ANALYZE criteord/cassandra_exporter:2.0.2    
INFO[0000] ANALYZE banzaicloud/vault-secrets-webhook:1.3.0 
INFO[0000] ANALYZE bitnami/zookeeper:3.6.1-debian-10-r37 
panic: runtime error: index out of range [1] with length 1

goroutine 30 [running]:
github.com/ivanilves/lstags/api/v1/registry/client/request.getNextLink(0xc00070a040, 0x4, 0x4, 0x4, 0xc0001b9510)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/request/request.go:122 +0x10e
github.com/ivanilves/lstags/api/v1/registry/client/request.Perform(0xc0000a0a80, 0x30, 0xc0000a4440, 0x5, 0x9250c7, 0x2, 0x0, 0x2, 0x6fc23ac00, 0x92cd89, ...)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/request/request.go:88 +0x396
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).TagData(0xc000356770, 0xc000354700, 0x11, 0x0, 0x0, 0x0, 0x0, 0xc000356770, 0x0)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:199 +0x379
github.com/ivanilves/lstags/tag/remote.FetchTags(0xc00023df20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/ivanilves/lstags/tag/remote/remote.go:69 +0x18f
github.com/ivanilves/lstags/api/v1.(*API).CollectTags.func1(0xc00023ca20, 0xc00023d560, 0xc00023df20, 0xc00023df80)
	/go/src/github.com/ivanilves/lstags/api/v1/v1.go:180 +0x139
created by github.com/ivanilves/lstags/api/v1.(*API).CollectTags
	/go/src/github.com/ivanilves/lstags/api/v1/v1.go:175 +0x25c

```

**Comment by ivanilves** [comment]
Nice catch! This is a [trivial] bug and I'll try to fix it ASAP.
