### ISSUE TITLE
panic: value method ... bearer.Token.Method called using nil *Token pointer

### ISSUE THREAD

**Issue by mfriedenhagen** [ivanilves/lstags#231]
* I am using latest release 1.2.20 (built from sources on macOS 11.4 using go version go1.16.5 darwin/amd64)
* However I saw the same happening with 1.2.18 on macOS and 1.2.20 downloaded from GitHub on Linux
* I try to check the attached file but get the following (this does not happen all the times but on Linux it never succeeds):
```
$ YAML_CONFIG=registry.gitlab.com.txt CONCURRENT_REQUESTS=16 WAIT_BETWEEN=0s RETRY_DELAY=1s RETRY_REQUESTS=2
time="2021-07-09T15:23:37Z" level=info msg="BATCH 1 of 1"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/spotbugs=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/flawfinder=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/mobsf=latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/kubesec=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/bandit=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/phpcs-security-audit=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/eslint=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/brakeman=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/nodejs-scan=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/semgrep=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/security-code-scan=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/sobelow=2,latest"
time="2021-07-09T15:23:37Z" level=info msg="ANALYZE registry.gitlab.com/gitlab-org/security-products/analyzers/pmd-apex=2,latest"
panic: value method github.com/ivanilves/lstags/api/v1/registry/client/auth/bearer.Token.Method called using nil *Token pointer

goroutine 254 [running]:
github.com/ivanilves/lstags/api/v1/registry/client/auth/bearer.(*Token).Method(0x0, 0xc000790bc0, 0x4170de)
	<autogenerated>:1 +0x49
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).repoToken(0xc00035fc70, 0xc0000be0f0, 0x2f, 0xc000790cb8, 0x40bc76, 0xc00038a660, 0x60)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:179 +0x47b
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).v1TagOptions(0xc00035fc70, 0xc0000be0f0, 0x2f, 0xc000142a94, 0x1, 0xc000142a94, 0x1, 0xc00038a600)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:333 +0x5d
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).Tag(0xc00035fc70, 0xc0000be0f0, 0x2f, 0xc000142a94, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:380 +0x130
github.com/ivanilves/lstags/tag/remote.FetchTags.func1(0xc00035fc70, 0xc00024ff80, 0xc000142a94, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/ivanilves/lstags/tag/remote/remote.go:104 +0x8b
created by github.com/ivanilves/lstags/tag/remote.FetchTags
	/go/src/github.com/ivanilves/lstags/tag/remote/remote.go:98 +0x46f
panic: value method github.com/ivanilves/lstags/api/v1/registry/client/auth/bearer.Token.Method called using nil *Token pointer

goroutine 278 [running]:
github.com/ivanilves/lstags/api/v1/registry/client/auth/bearer.(*Token).Method(0x0, 0xce5d20, 0x9d3da0)
	<autogenerated>:1 +0x49
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).repoToken(0xc00035fc70, 0xc0000be0f0, 0x2f, 0xc000001680, 0xc00036cec0, 0x4051aa, 0xc00039c660)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:179 +0x47b
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).tagDigest(0xc00035fc70, 0xc0000be0f0, 0x2f, 0xc000142a94, 0x1, 0xc000412180, 0xc000318aa8, 0xc00036cfb0, 0x6c46c2)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:274 +0x5d
github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).Tag.func1(0xc00035fc70, 0xc0000be0f0, 0x2f, 0xc000142a94, 0x1, 0xc00038a600, 0xc00038a660)
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:371 +0x70
created by github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).Tag
	/go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:370 +0xe0
```

[registry.gitlab.com.txt](https://github.com/ivanilves/lstags/files/6792484/registry.gitlab.com.txt)

**Comment by ivanilves** [comment]
Hi @mfriedenhagen 

Thank you for opening this issue, this looks like a bug in the code or some unforeseen interoperability issue.

Will figure it out.

**Comment by hulucc** [comment]
Same here.

**Comment by ivanilves** [comment]
Hi @hulucc @mfriedenhagen :wave: 

new release https://github.com/ivanilves/lstags/releases/tag/v1.2.21 should contain the fix.

Thank you!

**Comment by mfriedenhagen** [comment]
Thank you very much, @ivanilves for the quick fix. Seems to work here as intended. The fix looks magic, in most languages when something is null it is null :-)

**Comment by ivanilves** [comment]
You are very welcome! :handshake: 

Yes, Golang is special, it can have "container" structures which contain `nil` but are not `nil` themselves :smile:
