### ISSUE TITLE
panic after 429 retry twice

### ISSUE THREAD

**Issue by hulucc** [ivanilves/lstags#233]
and why 429 happend on first image analyzing ?
```
lstags-57b8db8bd4-x5jg4 lstags time="2021-07-22T08:21:47Z" level=info msg="BATCH 1 of 9"
lstags-57b8db8bd4-x5jg4 lstags time="2021-07-22T08:21:47Z" level=info msg="ANALYZE quay.io/rmarasch/oomhero:latest"
lstags-57b8db8bd4-x5jg4 lstags time="2021-07-22T08:21:47Z" level=info msg="ANALYZE node=10.15.3-jessie,12-buster,13-buster,14-buster,15-buster,14.17.3"
lstags-57b8db8bd4-x5jg4 lstags Will retry 'https://registry.hub.docker.com/v2/library/node/manifests/10.15.3-jessie' [v2] in a 2s
lstags-57b8db8bd4-x5jg4 lstags => Error: Bad response status: 429 Too Many Requests >> https://registry.hub.docker.com/v2/library/node/manifests/10.15.3-jessie
lstags-57b8db8bd4-x5jg4 lstags Will retry 'https://registry.hub.docker.com/v2/library/node/manifests/10.15.3-jessie' [v2] in a 4s
lstags-57b8db8bd4-x5jg4 lstags => Error: Bad response status: 429 Too Many Requests >> https://registry.hub.docker.com/v2/library/node/manifests/10.15.3-jessie
lstags-57b8db8bd4-x5jg4 lstags panic: runtime error: invalid memory address or nil pointer dereference
lstags-57b8db8bd4-x5jg4 lstags [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f4238]
lstags-57b8db8bd4-x5jg4 lstags
lstags-57b8db8bd4-x5jg4 lstags goroutine 40 [running]:
lstags-57b8db8bd4-x5jg4 lstags github.com/ivanilves/lstags/api/v1/registry/client/request.Perform(0xc00047d950, 0x48, 0xc000528900, 0x855, 0x927fa7, 0x2, 0x800, 0x2, 0x1dcd65000, 0xc00047d950, ...)
lstags-57b8db8bd4-x5jg4 lstags  /go/src/github.com/ivanilves/lstags/api/v1/registry/client/request/request.go:116 +0x3f8
lstags-57b8db8bd4-x5jg4 lstags github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).tagDigest(0xc00032e690, 0xc0001ee0e0, 0xc, 0xc00008e61d, 0xe, 0x0, 0x0, 0x5, 0xc0002f2240)
lstags-57b8db8bd4-x5jg4 lstags  /go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:280 +0x2a5
lstags-57b8db8bd4-x5jg4 lstags github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).Tag.func1(0xc00032e690, 0xc0001ee0e0, 0xc, 0xc00008e61d, 0xe, 0xc00008e120, 0xc00008e180)
lstags-57b8db8bd4-x5jg4 lstags  /go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:372 +0x70
lstags-57b8db8bd4-x5jg4 lstags created by github.com/ivanilves/lstags/api/v1/registry/client.(*RegistryClient).Tag
lstags-57b8db8bd4-x5jg4 lstags  /go/src/github.com/ivanilves/lstags/api/v1/registry/client/client.go:371 +0xe0
```

**Comment by ivanilves** [comment]
Rate limiting :sweat_smile: It gets more severe on DockerHub side.

**Comment by ivanilves** [comment]
Consider concurrency adjustment (see lstags help) :wink:
